title: El-Fadel's Blog
email: bonfohelfadel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elfadel.github.io"
linkedin_username: elfadel
github_username:  elfadel
twitter_username: ElFadel_Bonfoh

# Build settings
# theme: minima

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
