baseURL: https://elfadel.github.io/

languageCode: en-us
title: "El-Fadel Bonfoh"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Enable Analytics
analytics:
  enabled: true
  services:
    # Google Analytics
    google:
      id: G-S2D3DBW954
    # # CounterDev
    # counterDev:
    #   id: <your counterdev id>
    # # GoatCounter
    # goatCounter:
    #   code: <your goat counter code>
    # # Matomo / Piwik
    # matomo:
    #   instance: matomo.example.com
    #   siteId: 1 # Or any other number

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/elfadel/elfadel.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  #newsletter:
   # enable: true

  background: "images/background3.jpg"

  logo:
    main: images/logo_author.png
    inverted: images/logo_author.png
    favicon: images/logo_author.png